Import 3Dmesh Bookshelf
BautistaDiSanto/godot-melee pull request #1
Opened 2023-09-06 02:07 UTC by thedudenes

Le meti tales assets

2023-09-06 02:10 UTC, BautistaDiSanto requested changes
che veo que ya un asset de la puerta que nos e utiliza

2023-09-06 02:10 UTC, BautistaDiSanto commented on Assets 3D/BookShelf_TexturesCom_DoorsWoodSingleOld0226_S.png
che veo que este asset de la puerta no se esta utilizando, que onda gato?

2023-09-06 02:11 UTC, thedudenes commented on Assets 3D/BookShelf_TexturesCom_DoorsWoodSingleOld0226_S.png
Es la texture del mueble GIL

2023-09-11 23:56 UTC, BautistaDiSanto approved these changes

2023-09-11 23:56 UTC, merged